window_opacity = 0.95
colors.draw_bold_text_with_bright_colors = false
"window.opacity" = 0.99
"window.dynamic_title" = true
live_config_reload = true

[window]
opacity = 0.9
[window.position]
x = 0
y = 0

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 58
lines = 26

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 16

[colors.primary]
background = "0x181818"
foreground = "0xd8d8d8"

[colors.cursor]
text = "0x181818"
cursor = "0xd8d8d8"

[colors.normal]
black = "0x181818"
red = "0xab4642"
green = "0xa1b56c"
yellow = "0xf7ca88"
blue = "0x7cafc2"
magenta = "0xba8baf"
cyan = "0x86c1b9"
white = "0xd8d8d8"

[colors.bright]
black = "0x585858"
red = "0xab4642"
green = "0xa1b56c"
yellow = "0xf7ca88"
blue = "0x7cafc2"
magenta = "0xba8baf"
cyan = "0x86c1b9"
white = "0xf8f8f8"

[[colors.indexed_colors]]
index = 16
color = "0xdc9656"

[[colors.indexed_colors]]
index = 17
color = "0xa16946"

[[colors.indexed_colors]]
index = 18
color = "0x282828"

[[colors.indexed_colors]]
index = 19
color = "0x383838"

[[colors.indexed_colors]]
index = 20
color = "0xb8b8b8"

[[colors.indexed_colors]]
index = 21
color = "0xe8e8e8"

[bell]
animation = "EaseOutExpo"
duration = 300
color = "0xffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
unfocused_hollow = true

[mouse.hints]
modifiers = "Command"

  [mouse.hints.launcher]
  program = "open"
